config/routes.rb
Rails.application.routes.draw do
  resources :tags, only: [:index, :create, :show]
  resources :tracks, only: [:index]
  resources :likes, only: [:index, :create]
  resources :favourites, only: [:index, :create]

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'tracks#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable, :trackable
  has_many :tracks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :track_tags, dependent: :destroy
	has_many :tracks, :through => :track_tags
	has_many :user_tags, dependent: :destroy
	validates_uniqueness_of :value
	validates_presence_of :value
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :admin_user
  has_many :track_tags, dependent: :destroy
  has_many :tags, :through => :track_tags

  has_many :user_likes, dependent: :destroy
  has_many :user_favourites, dependent: :destroy

  validates_presence_of :title, :admin_user
  validates_uniqueness_of :title
  mount_uploader :audio, AudioUploader
end

app/models/track_tag.rb
class TrackTag < ApplicationRecord
  belongs_to :track, foreign_key: 'track_id'
  belongs_to :tag, foreign_key: 'tag_id'
  validates_uniqueness_of :tag_id, scope: :track_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_tags, dependent: :destroy
  has_many :tags, :through => :user_tags

  has_many :user_favourites, dependent: :destroy
  has_many :favourites, through: :user_favourites, source: :track

  has_many :user_likes, dependent: :destroy
  has_many :likes, through: :user_likes, source: :track

  validates_presence_of :first_name, :last_name

  def set_user_tags(ids)
    tags = Tag.find(ids)
    self.tags = tags
    self.save
  end

  def swap_track_liked(tracks)
    if self.likes.where(id: tracks.ids).empty?
      self.likes << tracks
    else
      self.likes.delete(tracks)
    end
    self.save
  end

  def swap_track_favourites(tracks)
    if self.favourites.where(id: tracks.ids).empty?
      self.favourites << tracks
    else
      self.favourites.delete(tracks)
    end
    self.save
  end
end

app/models/user_favourite.rb
class UserFavourite < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :track, foreign_key: 'track_id'
  validates_uniqueness_of :track_id, scope: :user_id
end

app/models/user_like.rb
class UserLike < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :track, foreign_key: 'track_id'
  validates_uniqueness_of :track_id, scope: :user_id
end

app/models/user_tag.rb
class UserTag < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :tag, foreign_key: 'tag_id'
  validates_uniqueness_of :tag_id, scope: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :admin
  before_action :set_tags, except: :admin
  before_action :configure_permitted_parameters, if:  :devise_controller?

protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  def set_tags
    @tags_sidebar = Tag.all
  end

end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    user = current_user
    if params["trackId"].present?
      track_id = params["trackId"].to_i
      tracks = Track.where(id: track_id)
      user.swap_track_favourites(tracks)
    end
  end

  def index
    @user = current_user
    @tracks = current_user.favourites
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  skip_before_action :verify_authenticity_token
  def create
    user = current_user
    if params["trackId"].present?
      track_id = params["trackId"].to_i
      tracks = Track.where(id: track_id)
      user.swap_track_liked(tracks)
    end
  end

  def index
    @user = current_user
    @tracks = current_user.likes
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
    @user = current_user
  end

  def create
    ids = params['options']
    ids = [] if ids.nil?
    current_user.set_user_tags(ids)
    redirect_to root_path
  end

  def show
    @tag = Tag.find(params[:id])
    trackTag = TrackTag.where(tag_id: params[:id])
    track_ids = trackTag.select(:track_id)
    @tracks = Track.where(id: track_ids)
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  def index
    if current_user.tags.empty?
      redirect_to tags_path
    end
    @user = current_user
    tracksFilter = params[:track]
    @tracks = nil

    if (tracksFilter == nil)
      userTags = UserTag.where(user_id: @user.id)
      tag_ids = userTags.select(:tag_id)
      trackTag = TrackTag.where(tag_id: tag_ids)
      track_ids = trackTag.select(:track_id)
      @tracks = Track.where(id: track_ids)
      @header_title = "Your relevant tracks"
    else
      @header_title = "Your search results for: " + tracksFilter
      @tracks = Track.where("lower(title) LIKE :query", query: "%#{tracksFilter.downcase}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header_panel.html.erb
<header class="bg-white-only header header-md navbar navbar-fixed-top-xs">
    <div class="navbar-header aside bg-info nav-xs"><a class="btn btn-link visible-xs"
                                                       data-toggle="class:nav-off-screen,open"
                                                       data-target="#nav,html"> <i class="icon-list"></i> </a>
                                                       <a
            href="/" class="navbar-brand text-lt"> <i
            class="icon-earphones"></i> <img src="/assets/logo.png" alt="." class="hide">
        <span class="hidden-nav-xs m-l-sm">Musik</span> </a> <a class="btn btn-link visible-xs"
                                                                data-toggle="dropdown" data-target=".user"> <i
            class="icon-settings"></i> </a></div>

    <%= form_tag(tracks_path, method: :get, :class => 'navbar-form navbar-left input-s-lg m-t m-l-n-xs hidden-xs') do %>
    <div class="form-group">
        <div class="input-group"><span class="input-group-btn"> <button type="submit"
                                                                        class="btn btn-sm bg-white btn-icon rounded"><i
                class="fa fa-search"></i></button>
               </span>
               <%= text_field_tag :track, "", class: 'form-control input-sm no-border rounded', placeholder: 'Search tracks' %>
              </div>
    </div>
    <% end %>

    <div class="navbar-right ">
        <ul class="nav navbar-nav m-n hidden-xs nav-user user">
            <li class="dropdown"><a class="dropdown-toggle bg clear" data-toggle="dropdown"> <span
                    class="thumb-sm avatar pull-right m-t-n-sm m-b-n-sm m-l-sm"> <img
                    src="/assets/a0.png" alt="..."> </span> <%= current_user.first_name + ' ' + current_user.last_name %><b class="caret"></b>
            </a>
                <ul class="dropdown-menu animated fadeInRight">
                    <li><a href="/users/edit">Edit Profile</a></li>
                    <li><a href="/favourites"> <span
                            class="badge bg-danger pull-right"><%= current_user.favourites.count%></span> Favorites </a></li>
                    <li><a href="/likes"> <span
                            class="badge bg-safe pull-right"><%= current_user.likes.count%></span> Likes </a></li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
                    </li>
                </ul>
            </li>
        </ul>
    </div>
</header>

app/views/layouts/_left_panel.html.erb
<aside class="bg-black dk nav-xs aside hidden-print" id="nav">
    <section class="vbox">
        <section class="w-f-md scrollable">
            <div class="slimScrollDiv"
                 style="position: relative; overflow: hidden; width: auto; height: 616px;">
                <div data-height="auto" data-disable-fade-out="true" data-distance="0"
                     data-size="10px" data-railopacity="0.2"
                     style="overflow: hidden; width: auto; height: 616px;"> <!-- nav -->
                    <nav class="nav-primary hidden-xs">
                        <ul class="nav bg clearfix">
                            <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"> Discover</li>
                            <!-- <li><a href=""> <i
                                    class="icon-disc icon text-success"></i> <span class="font-bold">H</span>
                            </a></li> -->
                            <!-- <li><a href="http://flatfull.com/themes/musik/genres.html"> <i
                                    class="icon-music-tone-alt icon text-info"></i> <span class="font-bold">Genres</span>
                            </a></li>
                            <li><a href="http://flatfull.com/themes/musik/events.html"> <i
                                    class="icon-drawer icon text-primary-lter"></i> <b
                                    class="badge bg-primary pull-right">6</b> <span
                                    class="font-bold">Events</span> </a></li>
                            <li><a href="http://flatfull.com/themes/musik/listen.html"> <i
                                    class="icon-list icon text-info-dker"></i> <span class="font-bold">Listen</span>
                            </a></li>
                            <li><a href="http://flatfull.com/themes/musik/video.html" data-target="#content"
                                   data-el="#bjax-el" data-replace="true"> <i
                                    class="icon-social-youtube icon text-primary"></i> <span
                                    class="font-bold">Video</span> </a></li>
                            <li class="m-b hidden-nav-xs"></li> -->
                        </ul>
                        <!-- <ul class="nav" data-ride="collapse">
                            <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"> Interface</li>
                            <li><a href="http://flatfull.com/themes/musik/index.html#" class="auto"> <span
                                    class="pull-right text-muted"> <i class="fa fa-angle-left text"></i> <i
                                    class="fa fa-angle-down text-active"></i> </span> <i
                                    class="icon-screen-desktop icon"> </i> <span>Layouts</span> </a>
                                <ul class="nav dk text-sm">
                                    <li><a href="http://flatfull.com/themes/musik/layout-color.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Color option</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/layout-boxed.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Boxed layout</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/layout-fluid.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Fluid layout</span>
                                    </a></li>
                                </ul>
                            </li>
                            <li><a href="http://flatfull.com/themes/musik/index.html#" class="auto"> <span
                                    class="pull-right text-muted"> <i class="fa fa-angle-left text"></i> <i
                                    class="fa fa-angle-down text-active"></i> </span> <i
                                    class="icon-chemistry icon"> </i> <span>UI Kit</span> </a>
                                <ul class="nav dk text-sm">
                                    <li><a href="http://flatfull.com/themes/musik/buttons.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Buttons</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/icons.html" class="auto">
                                        <b class="badge bg-info pull-right">369</b> <i
                                            class="fa fa-angle-right text-xs"></i> <span>Icons</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/grid.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Grid</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/widgets.html"
                                           class="auto"> <b class="badge bg-dark pull-right">8</b> <i
                                            class="fa fa-angle-right text-xs"></i> <span>Widgets</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/components.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Components</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/list.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>List group</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/index.html#table"
                                           class="auto"> <span class="pull-right text-muted"> <i
                                            class="fa fa-angle-left text"></i> <i
                                            class="fa fa-angle-down text-active"></i> </span> <i
                                            class="fa fa-angle-right text-xs"></i> <span>Table</span> </a>
                                        <ul class="nav dker">
                                            <li>
                                                <a href="http://flatfull.com/themes/musik/table-static.html">
                                                    <i class="fa fa-angle-right"></i>
                                                    <span>Table static</span> </a></li>
                                            <li>
                                                <a href="http://flatfull.com/themes/musik/table-datatable.html">
                                                    <i class="fa fa-angle-right"></i> <span>Datatable</span>
                                                </a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/index.html#form"
                                           class="auto"> <span class="pull-right text-muted"> <i
                                            class="fa fa-angle-left text"></i> <i
                                            class="fa fa-angle-down text-active"></i> </span> <i
                                            class="fa fa-angle-right text-xs"></i> <span>Form</span> </a>
                                        <ul class="nav dker">
                                            <li>
                                                <a href="http://flatfull.com/themes/musik/form-elements.html">
                                                    <i class="fa fa-angle-right"></i>
                                                    <span>Form elements</span> </a></li>
                                            <li>
                                                <a href="http://flatfull.com/themes/musik/form-validation.html">
                                                    <i class="fa fa-angle-right"></i>
                                                    <span>Form validation</span> </a></li>
                                            <li><a href="http://flatfull.com/themes/musik/form-wizard.html">
                                                <i class="fa fa-angle-right"></i> <span>Form wizard</span>
                                            </a></li>
                                        </ul>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/chart.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Chart</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/portlet.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Portlet</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/timeline.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Timeline</span>
                                    </a></li>
                                </ul>
                            </li>
                            <li><a href="http://flatfull.com/themes/musik/index.html#" class="auto"> <span
                                    class="pull-right text-muted"> <i class="fa fa-angle-left text"></i> <i
                                    class="fa fa-angle-down text-active"></i> </span> <i
                                    class="icon-grid icon"> </i> <span>Pages</span> </a>
                                <ul class="nav dk text-sm">
                                    <li><a href="http://flatfull.com/themes/musik/profile.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Profile</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/blog.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Blog</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/invoice.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Invoice</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/gmap.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Google Map</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/jvectormap.html"
                                           class="auto"> <i class="fa fa-angle-right text-xs"></i> <span>Vector Map</span>
                                    </a></li>
                                    <li><a href="http://flatfull.com/themes/musik/signin.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Signin</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/signup.html" class="auto">
                                        <i class="fa fa-angle-right text-xs"></i> <span>Signup</span> </a>
                                    </li>
                                    <li><a href="http://flatfull.com/themes/musik/404.html" class="auto"> <i
                                            class="fa fa-angle-right text-xs"></i> <span>404</span> </a>
                                    </li>
                                </ul>
                            </li>
                        </ul> -->
                        <!-- <ul class="nav text-sm">
                            <li class="hidden-nav-xs padder m-t m-b-sm text-xs text-muted"><span
                                    class="pull-right"><a
                                    href="http://flatfull.com/themes/musik/index.html#"><i
                                    class="icon-plus i-lg"></i></a></span> Playlist
                            </li>
                            <li><a href="http://flatfull.com/themes/musik/index.html#"> <i
                                    class="icon-music-tone icon"></i> <span>Hip-Pop</span> </a></li>
                            <li><a href="http://flatfull.com/themes/musik/index.html#"> <i
                                    class="icon-playlist icon text-success-lter"></i> <b
                                    class="badge bg-success dker pull-right">9</b> <span>Jazz</span> </a>
                            </li>
                        </ul> -->
                    </nav> <!-- / nav --> </div>
                <div class="slimScrollBar"
                     style="background: rgb(0, 0, 0); width: 10px; position: absolute; top: -44px; opacity: 0.4; display: none; border-radius: 7px; z-index: 99; right: 0px; height: 616px;"></div>
                <div class="slimScrollRail"
                     style="width: 10px; height: 100%; position: absolute; top: 0px; display: none; border-radius: 7px; background: rgb(51, 51, 51); opacity: 0.2; z-index: 90; right: 0px;"></div>
            </div>
        </section>
    </section>
</aside>

app/views/layouts/_right_panel.html.erb
<script>
function search() {

      // Retrieve the input field text and reset the count to zero
      var filter = $('#filter').val().toUpperCase().trim();

      // Loop through the comment list
      tags = document.getElementById("tags");
      var lis = tags.getElementsByTagName('li');
      for (i = 0; i < lis.length; i++) {
        tag = lis[i].getElementsByTagName("div");

        // If the list item does not contain the text phrase fade it out
        if (tag[0].id.toUpperCase().trim().indexOf(filter) < 0) {
          $('#' + lis[i].id).hide();
        } else {
          $('#' + lis[i].id).show();
        }

      }

    }
</script>
<aside class="aside-md bg-light dk" id="sidebar">
    <section class="vbox animated fadeInRight">
        <section class="w-f-md scrollable hover"><h4 class="font-thin m-l-md m-t">Connected</h4>
            <ul id= "tags" class="list-group no-bg no-borders auto m-t-n-xxs">
              <% @tags_sidebar.each do |tag| -%>
                <li id='li-<%=tag.value%>'class="list-group-item"><span
                        class="pull-left thumb-xs m-t-xs avatar m-l-xs m-r-sm"> <img
                        src="/images/tag.png" alt="..."
                        class="img-circle"></span>
                    <div id="<%= tag.value %>"class="clear">
                        <div>
                          <%= link_to tag.value, tag_path(tag.id)%>
                        </div>
                        <small class="text-muted"><%= tag.value %></small>
                    </div>
                </li>
              <% end %>
            </ul>
        </section>
        <footer class="footer footer-md bg-black">
            <form class="" role="search">
                <div class="form-group clearfix m-b-none">
                    <div class="input-group m-t m-b"><span class="input-group-btn"> <button
                            type="submit" class="btn btn-sm bg-empty text-muted btn-icon"><i
                            class="fa fa-search"></i></button> </span> <input type="text"
                                                                              id ="filter"
                                                                              class="form-control input-sm text-white bg-empty b-b b-dark no-border"
                                                                              placeholder="Search tags..."
                                                                              onkeyup="search()">
                    </div>
                </div>
            </form>
        </footer>
    </section>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="<% if user_signed_in? %>app js no-touch no-android chrome no-firefox no-iemobile no-ie no-ie8 no-ie10 no-ie11 no-ios no-ios7 ipad<% else %>bg-info<% end %>">
  <head>
    <meta charset="utf-8" />
    <title>MusicZone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="/assets/jplayer.flat.css" type="text/css" />
    <link rel="stylesheet" href="/assets/app.v1.css" type="text/css" />
    <style type="text/css">:root #content > #right > .dose > .dosesingle,
    :root #content > #center > .dose > .dosesingle {
        display: none !important;
    }</style>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <% if user_signed_in? %>
  <body cz-shortcut-listen="true">
  <section class="vbox">
    <%= render partial: 'layouts/header_panel' %>
      <section>
          <section class="hbox stretch">
            <%= render partial: 'layouts/left_panel' %>
            <section id="content">
                <section class="hbox stretch">
                    <%= yield %>
                    <%= render partial: 'layouts/right_panel' %>
                </section>
                <a href="http://flatfull.com/themes/musik/index.html#" class="hide nav-off-screen-block"
                   data-toggle="class:nav-off-screen,open" data-target="#nav,html"></a>
            </section>
          </section>
      </section>
  </section>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  </body>

  <% else %>
    <body class="bg-info">
      <section id="content" class="m-t-lg wrapper-md animated fadeInUp">
        <div class="container aside-xl">
          <a class="navbar-brand block" href="index.html">
            <span class="h1 font-bold">MusicZone</span>
          </a>
          <section class="m-b-lg">
            <% if notice %>
              <p class="alert alert-success"><%= notice %></p>
            <% end %>
            <% if alert %>
              <p class="alert alert-danger"><%= alert %></p>
            <% end %>
            <%= yield %>
          </section>
        </div>
      </section>
      <footer class="page-footer font-small blue pt-4">
        <div class="footer-copyright text-center padder">© <%= Time.now.year %> Copyright:
          <a href=""> MusicZone.com</a>
        </div>
      </footer>
    </body>
  <% end %>
</html>